import { Injectable } from '@nestjs/common';
import status from 'http-status';
import { Prisma } from '../../../generated/prisma/client';
import AppError from '../../../config/errorHelpers/AppError';
import prisma from '../../../shared/prisma';
import { IRequestUser } from '../../interfaces/requestUser.interface';

export interface PackagePayload { name: string; description?: string; price: number; facilityIds?: string[]; }
@Injectable()
export class PackageService {
  list(turfId: string) { return prisma.package.findMany({ where: { turfId, turf: { status: 'ACTIVE' } }, include: { facilities: { include: { facility: true } } }, orderBy: { name: 'asc' } }); }
  async listMine(user: IRequestUser, query?: { turfId?: string; search?: string; sortBy?: string; sortOrder?: string; page?: number; limit?: number; active?: boolean }) { const page = Math.max(1, query?.page ?? 1); const limit = Math.min(100, Math.max(1, query?.limit ?? 10)); const where: Prisma.PackageWhereInput = { turf: { ownerId: user.userId }, ...(query?.turfId ? { turfId: query.turfId } : {}), ...(query?.active !== undefined ? { active: query.active } : {}), ...(query?.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' } }, { description: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const sortField = ['name', 'price', 'active', 'createdAt'].includes(query?.sortBy ?? '') ? query?.sortBy! : 'createdAt'; const sortOrder = query?.sortOrder === 'asc' ? 'asc' : 'desc'; const [data, total] = await prisma.$transaction([prisma.package.findMany({ where, include: { facilities: { include: { facility: true } }, turf: { select: { name: true } } }, orderBy: { [sortField]: sortOrder }, skip: (page - 1) * limit, take: limit }), prisma.package.count({ where })]); return { data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  async findOne(user: IRequestUser, id: string) { const item = await prisma.package.findUnique({ where: { id }, include: { facilities: { include: { facility: true } }, turf: { select: { name: true } } } }); if (!item) throw new AppError(status.NOT_FOUND, 'Package not found'); await this.assertOwner(user, item.turfId); return item; }
  async create(user: IRequestUser, turfId: string, payload: PackagePayload) { await this.assertOwner(user, turfId); await this.assertFacilities(payload.facilityIds ?? []); return prisma.package.create({ data: { turfId, name: payload.name.trim(), description: payload.description, price: new Prisma.Decimal(payload.price), facilities: { create: (payload.facilityIds ?? []).map((facilityId) => ({ facilityId })) } }, include: { facilities: true } }); }
  async update(user: IRequestUser, id: string, payload: PackagePayload) { const item = await prisma.package.findUnique({ where: { id } }); if (!item) throw new AppError(status.NOT_FOUND, 'Package not found'); await this.assertOwner(user, item.turfId); await this.assertFacilities(payload.facilityIds ?? []); return prisma.$transaction(async (tx) => { await tx.packageFacility.deleteMany({ where: { packageId: id } }); return tx.package.update({ where: { id }, data: { name: payload.name.trim(), description: payload.description, price: new Prisma.Decimal(payload.price), facilities: { create: (payload.facilityIds ?? []).map((facilityId) => ({ facilityId })) } }, include: { facilities: true } }); }); }
  async delete(user: IRequestUser, id: string) { const item = await prisma.package.findUnique({ where: { id } }); if (!item) throw new AppError(status.NOT_FOUND, 'Package not found'); await this.assertOwner(user, item.turfId); return prisma.package.delete({ where: { id } }); }
  private async assertOwner(user: IRequestUser, turfId: string) { if (user.role !== 'ADMIN' || !(await prisma.turf.findFirst({ where: { id: turfId, ownerId: user.userId } }))) throw new AppError(status.FORBIDDEN, 'Turf access denied'); }
  private async assertFacilities(facilityIds: string[]) { const uniqueIds = [...new Set(facilityIds)]; const count = await prisma.facility.count({ where: { id: { in: uniqueIds } } }); if (count !== uniqueIds.length) throw new AppError(status.BAD_REQUEST, 'One or more facilities are invalid'); }
}
